export const MOBILE_E2EE_MAX_TEXT_PLAINTEXT_BYTES = 4 * 1024 * 1024
export const MOBILE_E2EE_MAX_BINARY_PLAINTEXT_BYTES = 8 * 1024 * 1024

export const MOBILE_E2EE_LEGACY_FRAME_OVERHEAD_BYTES = 40
export const MOBILE_E2EE_V2_FRAME_OVERHEAD_BYTES = 82

export const MOBILE_E2EE_LEGACY_MAX_TEXT_FRAME_BYTES =
  MOBILE_E2EE_MAX_TEXT_PLAINTEXT_BYTES + MOBILE_E2EE_LEGACY_FRAME_OVERHEAD_BYTES
export const MOBILE_E2EE_LEGACY_MAX_BINARY_FRAME_BYTES =
  MOBILE_E2EE_MAX_BINARY_PLAINTEXT_BYTES + MOBILE_E2EE_LEGACY_FRAME_OVERHEAD_BYTES
export const MOBILE_E2EE_V2_MAX_TEXT_FRAME_BYTES =
  MOBILE_E2EE_MAX_TEXT_PLAINTEXT_BYTES + MOBILE_E2EE_V2_FRAME_OVERHEAD_BYTES
export const MOBILE_E2EE_V2_MAX_BINARY_FRAME_BYTES =
  MOBILE_E2EE_MAX_BINARY_PLAINTEXT_BYTES + MOBILE_E2EE_V2_FRAME_OVERHEAD_BYTES

export const MOBILE_E2EE_LEGACY_MAX_TEXT_FRAME_BASE64_CHARACTERS =
  Math.ceil(MOBILE_E2EE_LEGACY_MAX_TEXT_FRAME_BYTES / 3) * 4
export const MOBILE_E2EE_V2_MAX_TEXT_FRAME_BASE64_CHARACTERS =
  Math.ceil(MOBILE_E2EE_V2_MAX_TEXT_FRAME_BYTES / 3) * 4
